### ISSUE TITLE
Improve handling of addresses without URL sheme

### ISSUE THREAD

**Issue by vitaut** [RedSilkSoftware/webtooth-extractor#1]
When entering an address without URL scheme, e.g. "www.google.com", the page doesn't load. It would be nice either to have the default URL scheme such as `http` or give some indication that the URL is invalid.

**Comment by patlecat** [comment]
Agreed.

**Comment by patlecat** [comment]
Fixed in a09957463ad2d44750f0f604d1117b06695e677c
