### ISSUE TITLE
Clicking "Scan webpage now" breaks scrolling in Web View

### ISSUE THREAD

**Issue by vitaut** [RedSilkSoftware/webtooth-extractor#2]
How to reproduce:
1. Start WebTooth Extractor
2. Wait till the start page opens
3. Observe that scrolling is working in Web View
4. Click "Scan webpage now"
5. Observe that the scrollbars disappear and the scrolling stopped working in Web View

**Comment by patlecat** [comment]
Noted, I have no idea what triggers this odd behavior. And the webview (with the webkit inside) is a bit of a black box. But I'll investigate it.

**Comment by patlecat** [comment]
Ok fixed it in: 70272cc480f3ede44e1c5dddbac039e2b65066ad
It was a problem created with a resize of the webview viewport that is necessary to create the screenshot.

**Comment by vitaut** [comment]
Thanks. It works great now.
