### ISSUE TITLE
Removing a filter

### ISSUE THREAD

**Issue by vitaut** [RedSilkSoftware/webtooth-extractor#3]
There doesn't seem to be a way to remove a filter. It would be nice if you could delete one by selecting it in Filter List and pressing the Delete key.

**Comment by patlecat** [comment]
It may be confusing but just as you create new filters with the specialized syntax can you delete them.

Example:
gugus;t#5 --> remove all 5 again with...

```
gugus*;d*
```

sugus;t --> remove with... 

```
sugus;d
```

I adopted this syntax to speed up the work of professional users, you can find the description in the tooltip and in the manual. Casual users would probably prefer icons to click on. I may consider this in a later release.
